package com.nttdocomo.security;

import opendoja.host.security.DoJaCryptoSupport;

/**
 * Acquires random numbers that can be used by the encryption function.
 */
public final class RandomNumberGenerator {
    private RandomNumberGenerator() {
    }

    /**
     * Acquires random numbers that can be used by the encryption function.
     * Random numbers generated by the random-number generator are returned with
     * the specified byte length.
     *
     * @param byteSize the length of the random numbers to acquire, in bytes
     * @return the random numbers as a byte array
     * @throws IllegalArgumentException if {@code byteSize} is 0 or less
     */
    public static synchronized byte[] getRandomNumber(int byteSize) {
        return DoJaCryptoSupport.randomBytes(byteSize);
    }
}
