package com.nttdocomo.ui;

import com.nttdocomo.util.EventListener;

/**
 * Defines the listener for component events.
 * Objects that receive events generated by components in the high-level API
 * implement this interface.
 *
 * @see Panel
 */
public interface ComponentListener extends EventListener {
    int BUTTON_PRESSED = 1;
    int SELECTION_CHANGED = 2;
    int TEXT_CHANGED = 3;

    void componentAction(Component component, int type, int param);
}
